name: Test and lint

on:
  pull_request:
    paths:
      - '**/*'
  push:
    branches: [main]

  workflow_dispatch:

  workflow_call:
    inputs:
      test_data_branch:
        type: string
        description: The branch in sdk-test-data to target for testcase files
        required: false
        default: main
      sdk_branch:
        type: string
        description: The branch of the SDK to test
        required: false

env:
  ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
  ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
  CI: true
  SDK_BRANCH: ${{ inputs.sdk_branch  || github.head_ref || github.ref_name || 'main' }}
  TEST_DATA_BRANCH: ${{ inputs.test_data_branch || 'main' }}

jobs:
  lint-test-sdk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['8', '11', '17', '21'] # Define the Java versions to test against
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Eppo-exp/sdk-common-jdk
          ref: ${{ env.SDK_BRANCH }}
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run tests
        run: make test branchName=${TEST_DATA_BRANCH}
