name: Test and lint

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  lint-test-sdk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['8', '11', '17'] # Define the Java versions to test against
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run tests
        run: ./gradlew check --no-daemon


      - name: Publish Snapshot artifact
        run: ./gradlew publish --no-daemon
