name: Publish SDK Snapshot artifact

on:
  push:
    branches: [main, tp/*]

env:
  CI: true

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    env:
      JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_TOKEN_USERNAME }}
      JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN_PASSWORD }}
      JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
      JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Download test data
        run: make test-data

      - name: Verify JReleaser
        run: ./gradlew jreleaserConfig --stacktrace

      - name: Stage artifacts
        run: ./gradlew clean publish -Psnapshot

      - name: Deploy to Maven Central
        run: ./gradlew jreleaserDeploy --stacktrace
